export const PROMOTION_LIST_REQUEST = 'PROMOTION_LIST_REQUEST'
export const PROMOTION_LIST_SUCCESS = 'PROMOTION_LIST_SUCCESS'
export const PROMOTION_URL_EXTRACTOR = 'PROMOTION_LIST_SUCCESS'
export const PROMOTION_LIST_FAIL = 'PROMOTION_LIST_FAIL'
