export const YOUTUBE_LIST_REQUEST = 'YOUTUBE_LIST_REQUEST'
export const YOUTUBE_LIST_SUCCESS = 'YOUTUBE_LIST_SUCCESS'
export const YOUTUBE_URL_EXTRACTOR = 'YOUTUBE_LIST_SUCCESS'
export const YOUTUBE_LIST_FAIL = 'YOUTUBE_LIST_FAIL'
